### ISSUE TITLE
Support

### ISSUE THREAD

**Issue by Flonixcorn** [nicolai256/audio_keyframe_deforum_DD_0.5#2]
This script does not work anymore, is this still supported?

**Comment by Flonixcorn** [comment]
ERROR:spleeter:ffmpeg binary not found

**Comment by Flonixcorn** [comment]
Traceback (most recent call last):
  File "X:\Downloads\Animate to BPM\audio_keyframe_deforum_DD_0.5\advanced_audio_splitter_keyframes.py", line 675, in <module>
    final_dict = service.process(args.stems,args.file, zoomspeed=args.zoomspeed, speed=args.speed)
  File "X:\Downloads\Animate to BPM\audio_keyframe_deforum_DD_0.5\advanced_audio_splitter_keyframes.py", line 307, in process
    dirs = os.listdir(f"{stems_dir}/" + filedircalc)
FileNotFoundError: [WinError 3] The system cannot find the path specified: 'outputs/audio'

**Comment by nicolai256** [comment]
Create the folder named outputs and put a folder named audio inside it
